### ISSUE TITLE
Optionally display charging / discharging time

### ISSUE THREAD

**Issue by Protoss78** [Protoss78/battery-status-icon#1]
Add a new attribute that controls the display of charging / discharging time depending on the current charging state. If the battery is charging display the remaining charge time. If the battery is currently not charging then display the remainig discharging time.

**Comment by Link2Twenty** [comment]
Have you got a UX in mind for this?

**Comment by Protoss78** [comment]
Not yet. The simplistic approach would be to display it in a simple text format (hh:mm), just like the percentage. Not sure how a graphic approach could look like.
In either case it should be possible to combine it with the current percentage label.

**Comment by Link2Twenty** [comment]
With the label, think it might be worth going the [paper-tooltip](https://elements.polymer-project.org/elements/paper-tooltip) route?

It would mean the user would have to mouse over (or tap on a touch screen device) the battery icon before they saw the extra information though.

**Comment by Protoss78** [comment]
Great idea. Wasn't aware of that element. 
The question for me then is if we should move the percentage label into the tooltip as well?
It would also make sense to make various tooltip parameters configurable through the battery-status-icon element. Like tooltip position and maybe even various animation parameters.

**Comment by Link2Twenty** [comment]
OK, I'll do a quick mock up see how you like it.

**Comment by Link2Twenty** [comment]
![tooltip](https://cloud.githubusercontent.com/assets/3534427/13817918/e2fba536-eb8b-11e5-8646-f275b05cb793.png)

I didn't know how to convert the numbers to times so just left them as is, works for getting an idea of the look though

**Comment by Protoss78** [comment]
Nice. Looks good to me. Although I like the additional icon in the tooltip, I wonder if it is not somehow redundant, as the actual battery icon already displays the charging symbol as well. 
Maybe we should add a progress symbol next to percentage and a clock symbol next to the time value instead? What do you think?

**Comment by Protoss78** [comment]
From iron-icons we could use device:data-usage for the progress and device:access-time for the time value. Just a suggestion though. :-)

**Comment by Link2Twenty** [comment]
Yeah, I felt the same, though I felt the need for some sort icon to indicate if the time remaining was until  full or until empty (the number changes depending on whether it's on charge or not).

**Comment by Link2Twenty** [comment]
I quite like having one icon that changes, oppose to an icon for each line. But it's you call :-)

**Comment by Link2Twenty** [comment]
(Maybe something as simple as an arrow up for on charge and an arrow down for discharge)

**Comment by Protoss78** [comment]
Ok. I get your point. What do you think of icons:trending-up and icons:trending-down from the iron-icons package?
https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html&active=iron-icons

**Comment by Link2Twenty** [comment]
![tooltip2](https://cloud.githubusercontent.com/assets/3534427/13819470/6b26acbc-eb91-11e5-9d76-2f39ee9daf67.png)

Here it is with them.

**Comment by Protoss78** [comment]
Looks good to me. What do you think?

**Comment by Link2Twenty** [comment]
Yeah it does the job, next we need to work out the math for converting the numbers (5549) into HH:MM and also have it catch null, 0 and infinity and make them a bit nicer.

**Comment by Protoss78** [comment]
Hmm. How about a simple compute function that works somehow like that:

```
if (!totalSeconds) {
    return '';
  }
  var hours   = Math.floor(totalSeconds / 3600);
  var minutes = Math.floor((totalSeconds - (hours * 3600)) / 60);
  return hours + ':' + minutes;
```

**Comment by Link2Twenty** [comment]
I've submitted a PR, before you merge it have a quick check that it's what you had in mind. Also I'm probably not going to be able to do the documentation updates until tomorrow (8am GMTish)

**Comment by Protoss78** [comment]
No worries. I've merged your changes and fixed the 2 minor problems with the missing dependency and the minute conversion. Since my schedule for tomorrow is pretty tight I probably won't have a lot time to update the documentation either. Not until the evening.
