### ISSUE TITLE
Add possibility to rotate battery status icon

### ISSUE THREAD

**Issue by Protoss78** [Protoss78/battery-status-icon#13]
Add a new property that provides a simple way to rotate the battery status icon:
- default (vertical)
- left-to-right (horizontal, battery drains from left to right)
- right-to-left (horizontal, battery drains from right to left)

**Comment by Link2Twenty** [comment]
You could do a quick easy solution

**Add to #battery-container:**

```
  -ms-transform: var(--battery-icon-rotate, rotate(0deg)); /* IE 9 */
  -webkit-transform: var(--battery-icon-rotate, rotate(0deg)); /* Chrome, Safari, Opera */
  transform: var(--battery-icon-rotate, rotate(0deg));
```

**As a style:**

```
  --battery-icon-rotate: rotate(270deg);
```

**EDIT:**
I've tested this method in IE, Edge, FF and Chrome and it works.

**Comment by Protoss78** [comment]
Thanks for the code sample. Maybe I'll find some time tomorrow to implement it. :-)
