### ISSUE TITLE
paper toast notifications on change

### ISSUE THREAD

**Issue by Link2Twenty** [Protoss78/battery-status-icon#14]
Is it worth having an option to do a [paper toast](https://elements.polymer-project.org/elements/paper-toast)? 
- If battery state changes (between charge and discharge)
- When fully charged
- If it reaches a threshold like 15%
- If autodetect is on but not supported.

**Comment by Protoss78** [comment]
I would prefer to implement the above mentioned different situations as events and let the user handle them on their own. The problems I see with the paper-toast implementation are the following:
- The messages would have to be translatable
- The user would have an icon that suddenly also generates UI notifications. Somehow that does not feel right for me. As a web component user I would not expect an icon to do that.

From an architecture perspective I'm not quite happy that the Battery API is used inside the battery-status-icon. I'm thinking about extracting that logic and creating a separate web component that would handle the Battery API. Maybe some kind of battery-status-behavior component.

**Comment by Link2Twenty** [comment]
Shall we put this on hold until the component is split then?

**Comment by Link2Twenty** [comment]
I think setting a few of the attributes to `notify: true` might be a good idea.

With the feature I was suggesting above just adding notify to charging would mean you could have an event listener

```JS
var batterySelector = document.querySelector('battery-status-icon');

batterySelector.addEventListener("charging-changed", function(){
  console.log("Device is charging: "+batterySelector.charging);
})
```

https://github.com/Protoss78/battery-status-icon/blob/master/battery-status-icon.html#L199

**Comment by Protoss78** [comment]
Just pushed a commit to master where I enabled notifications for charging and battery level. Also included it in documentation and the demo. Let me know what you think of it. 😄

**Comment by Link2Twenty** [comment]
Yep that's perfect 🙂
