### ISSUE TITLE
unexpected token

### ISSUE THREAD

**Issue by BaptisteCool** [Protoss78/battery-status-icon#16]
I would like to use it but i have an error line 1 :  'Unexpected token'

I don't know if is it from my computer or in the code.

Could you check that ?

Thanks

**Comment by Protoss78** [comment]
Can you share more details? Sample code or a repo link?

**Comment by BaptisteCool** [comment]
I have that when i import it
<script src="/bower_components/battery-status-icon/battery-status-icon.html"></script>

![image](https://user-images.githubusercontent.com/6760432/39519571-98f5b5cc-4e07-11e8-8bfc-7e574c89cb2c.png)
![image](https://user-images.githubusercontent.com/6760432/39519591-ae1bd63e-4e07-11e8-8f5e-8a9cdc70b5c7.png)

**Comment by BaptisteCool** [comment]
Hep, my fault, duplicate a script import line instead of link import !
